name: Sync from Surge

on:
  schedule:
    - cron: '0 * * * *' # 每60分钟运行一次
  workflow_dispatch: # 允许手动触发

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Shadowrocket
        uses: actions/checkout@v3

      - name: Clone Surge Repository
        run: git clone https://github.com/USNOCTURNE90/Surge.git

      - name: Sync Content
        run: |
          rsync -av --delete --exclude='.git' --exclude='.github' Surge/ ./ || [ $? -eq 24 ]

      - name: Commit and Push Changes
        run: |
          git config --local user.name "GitHub Action"
          git config --local user.email "action@github.com"
          git add .
          git commit -m "Sync content from Surge" || echo "No changes to commit"
          git push